services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
    volumes:
      - schools-db:/var/lib/postgresql/data
  app:
    image: my-node-app:latest
    ports:
      - 13000:3000
volumes:
  schools-db:
